---

- name: Solr | Configuring jetty server
  template:
    src: "{{ solr_templates_dir }}/jetty.xml.j2"
    dest: "{{ solr_installation_dir }}/server/etc/jetty.xml"
    force: true
  notify: restart Solr

- name: Solr | Configuring jetty server http
  template:
    src: "{{ solr_templates_dir }}/jetty-http.xml.j2"
    dest: "{{ solr_installation_dir }}/server/etc/jetty-http.xml"
    force: true
  notify: restart Solr

- name: Solr | Configuring Solr init script
  template:
    src: "{{ solr_templates_dir }}/solr.in.sh.j2"
    dest: "{{ solr_config_file_dir }}"
    force: true
  notify: restart Solr

- name: Solr | Configure Solr service
  template:
    src: "{{ solr_template_service }}"
    dest: /lib/systemd/system/solr.service
    force: true
  notify: restart Solr

- name: Solr | Configuring Solr properties
  template:
    src: "{{ solr_templates_dir }}/solr.xml.j2"
    dest: "{{ solr_data_dir }}/solr.xml"
    force: true
  notify: restart Solr

- name: Solr | Configuring logging
  template:
    src: "{{ solr_templates_dir }}/{{ solr_log_config_file }}.j2"
    dest: "{{ solr_installation_dir }}/{{ solr_log_config_file }}"
    force: true
  notify: restart Solr

- name: Solr | Gather OS specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Solr | Install maven_artifact module required packages
  package:
    name: "{{ solr_external_libraries_required_packages }}"
    state: present
  notify: restart Solr
  when: solr_external_libraries is defined and solr_external_libraries|length > 0

- name: Solr | Copy external libraries
  maven_artifact:
    group_id: "{{ item.group_id }}"
    artifact_id: "{{ item.artifact_id }}"
    version: "{{ item.version }}"
    repository_url: "{{ solr_external_libraries_repository_url }}"
    dest: "{{ solr_external_libraries_destination_path }}"
    mode: 0644
    keep_name: true
  with_items: "{{ solr_external_libraries }}"
  notify: restart Solr
  when: solr_external_libraries is defined and solr_external_libraries|length > 0

- name: Solr | Force handlers
  meta: flush_handlers

- name: Solr | Wait for Solr to fully startup before continue
  uri:
    url: "http://{{ solr_host }}:{{ solr_port }}/solr"
    status_code: 200
  retries: "100"
  delay: "1"
  register: result
  until: result.status == 200
  changed_when: false
