---

- name: Solr | Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ solr_sysctl_required_packages }}"
  when: solr_sysctl_required_packages is defined

- name: Solr | Apply sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
  with_items: "{{ solr_sysctl_properties }}"
  when: solr_sysctl_properties is defined
  notify: reboot machine

- name: Solr | Disable SWAP (1/2)
  shell: |
    swapoff -a
  when: solr_disable_swap

- name: Solr | Disable SWAP in fstab (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: solr_disable_swap

- name: Solr | Force handlers
  meta: flush_handlers
